version: "3"

services:
  mongo:
    container_name: mongoDB_dev
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis_dev
    image: redis
    volumes:
      - ./data:/redis/db
    ports:
      - "6379:6379"